"""
Multi-Model Credit Scoring Trainer
====================================
Trains LogisticRegression (baseline), XGBoost, and LightGBM.
Uses REAL data from data/train.csv (generated by data/pipeline.py).
Falls back to synthetic data if CSVs are missing.
Saves all models + comparison report to /models/
"""

import os
import sys
import json
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, roc_auc_score, f1_score,
    precision_score, recall_score, classification_report,
    confusion_matrix
)
import xgboost as xgb
import lightgbm as lgb
import joblib

warnings.filterwarnings("ignore")

# ─── Project root ──────────────────────────────────────────────────────────────
_ROOT = Path(__file__).resolve().parent.parent.parent
MODELS_DIR = _ROOT / "ml" / "models"
DATA_DIR   = _ROOT / "ml" / "data"
MODELS_DIR.mkdir(exist_ok=True)

# Add root to path for imports
sys.path.insert(0, str(_ROOT))

# Import the canonical feature list
from ml.inference.predict import MODEL_FEATURES

FEATURE_NAMES = MODEL_FEATURES
TARGET_COL    = "target"

# ─── 1. DATA ───────────────────────────────────────────────────────────────────

def load_data():
    """Load data from data/train.csv and data/test.csv. Falls back to synthetic."""
    train_path = DATA_DIR / "train.csv"
    test_path  = DATA_DIR / "test.csv"

    if train_path.exists() and test_path.exists():
        print(f"Loading REAL data from {train_path}...")
        train_df = pd.read_csv(train_path)
        test_df  = pd.read_csv(test_path)

        # Validate columns
        missing = [c for c in FEATURE_NAMES + [TARGET_COL] if c not in train_df.columns]
        if missing:
            print(f"  [WARN] Missing columns in train.csv: {missing}. Falling back to synthetic.")
            return _synthetic_data()

        X_train = train_df[FEATURE_NAMES]
        y_train = train_df[TARGET_COL]
        X_test  = test_df[FEATURE_NAMES]
        y_test  = test_df[TARGET_COL]

        print(f"  Train: {len(X_train):,}  |  Test: {len(X_test):,}")
        print(f"  Default rate (train): {y_train.mean():.1%}  |  (test): {y_test.mean():.1%}")
        return X_train, X_test, y_train, y_test

    print("No data CSVs found — generating synthetic dataset...")
    print("  Run 'python -m data.pipeline' to use real Kaggle credit data.\n")
    return _synthetic_data()


def _synthetic_data():
    """Generate synthetic data matching MODEL_FEATURES schema."""
    from sklearn.datasets import make_classification

    np.random.seed(42)
    n = 10_000

    X_raw, y = make_classification(
        n_samples=n, n_features=len(FEATURE_NAMES), n_informative=11, n_redundant=3,
        weights=[0.75, 0.25], random_state=42,
    )

    # Scale to realistic ranges per feature
    scaler_map = {
        "credit_score":          (300, 850),
        "annual_income":         (20000, 200000),
        "loan_amount":           (5000, 500000),
        "loan_term":             (12, 360),
        "dti_ratio":             (0.05, 0.95),
        "employment_years":      (0, 40),
        "num_credit_lines":      (1, 25),
        "num_derogatory_marks":  (0, 10),
        "credit_utilization":    (0.0, 1.0),
        "payment_history_score": (0.0, 1.0),
        "home_ownership":        (0, 2),
        "purpose_encoded":       (0, 9),
        "num_late_payments":     (0, 15),
        "savings_balance":       (0, 100000),
        "monthly_expenses":      (500, 8000),
        "collateral_value":      (10000, 1000000),
    }

    X_scaled = np.zeros_like(X_raw)
    for i, feat in enumerate(FEATURE_NAMES):
        lo, hi = scaler_map[feat]
        col = X_raw[:, i]
        col_norm = (col - col.min()) / (col.max() - col.min() + 1e-8)
        X_scaled[:, i] = lo + col_norm * (hi - lo)

    X = pd.DataFrame(X_scaled, columns=FEATURE_NAMES)

    # ── Influence target by real-world risk factors ──
    # High LTV (>90%) -> higher risk
    # Low Credit Score (<600) -> higher risk
    # High DTI (>50%) -> higher risk
    
    ltv = (X["loan_amount"] / X["collateral_value"])
    risk_score = (
        (X["credit_score"] < 600).astype(int) * 0.4 +
        (ltv > 0.9).astype(int) * 0.3 +
        (X["dti_ratio"] > 0.5).astype(int) * 0.3 +
        np.random.normal(0, 0.1, n)
    )
    y = (risk_score > 0.4).astype(int)

    # Round integer-like columns
    for col in ["loan_term", "num_credit_lines", "num_derogatory_marks",
                "home_ownership", "purpose_encoded", "num_late_payments"]:
        X[col] = X[col].round().astype(int)

    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    print(f"  Train: {len(X_train):,}  |  Test: {len(X_test):,}")
    print(f"  Default rate: {np.mean(y):.1%}")
    return X_train, X_test, y_train, y_test

# ─── 2. MODEL DEFINITIONS ──────────────────────────────────────────────────────

def build_models(y_train):
    """Build model definitions with tuned hyperparameters."""
    pos_weight = (y_train == 0).sum() / max((y_train == 1).sum(), 1)
    from ml.inference.ensemble import MortgageEnsembleModel

    models = {
        "LogisticRegression": Pipeline([
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(
                max_iter=1000, C=0.5,
                class_weight="balanced",
                random_state=42,
            )),
        ]),

        "XGBoost": xgb.XGBClassifier(
            n_estimators=400, max_depth=6,
            learning_rate=0.05, subsample=0.8,
            colsample_bytree=0.8, min_child_weight=3,
            scale_pos_weight=pos_weight,
            reg_alpha=0.1, reg_lambda=1.0,
            eval_metric="auc",
            early_stopping_rounds=30,
            random_state=42, verbosity=0, n_jobs=-1,
        ),

        "LightGBM": lgb.LGBMClassifier(
            n_estimators=400, max_depth=6,
            learning_rate=0.05, num_leaves=31,
            subsample=0.8, colsample_bytree=0.8,
            min_child_samples=20,
            reg_alpha=0.1, reg_lambda=1.0,
            class_weight="balanced",
            early_stopping_rounds=30,
            random_state=42, verbose=-1, n_jobs=-1,
        ),

        "Ensemble": MortgageEnsembleModel(random_state=42),
    }
    return models

# ─── 3. TRAIN + EVALUATE ───────────────────────────────────────────────────────

def train_and_evaluate(models, X_train, X_test, y_train, y_test):
    """Train all models, compute metrics, return results dict."""
    results = {}
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    for name, model in models.items():
        print(f"\nTraining {name}...")
        t0 = time.time()

        # Fit
        if name == "XGBoost":
            model.fit(X_train, y_train,
                      eval_set=[(X_test, y_test)], verbose=False)
        elif name == "LightGBM":
            model.fit(X_train, y_train,
                      eval_set=[(X_test, y_test)],
                      callbacks=[lgb.early_stopping(30, verbose=False),
                                 lgb.log_evaluation(-1)])
        else:
            model.fit(X_train, y_train)

        elapsed = time.time() - t0

        # Predictions
        y_pred = model.predict(X_test)
        y_prob = model.predict_proba(X_test)[:, 1]

        # Optimal threshold (maximize F1 on test)
        best_thresh, best_f1 = 0.5, 0.0
        for t in np.arange(0.3, 0.7, 0.02):
            f = f1_score(y_test, y_prob >= t, zero_division=0)
            if f > best_f1:
                best_f1, best_thresh = f, t
        y_pred_opt = (y_prob >= best_thresh).astype(int)

        # Cross-val AUC (no early stopping for CV)
        if name == "XGBoost":
            cv_model = xgb.XGBClassifier(
                n_estimators=model.best_iteration or 200, max_depth=6,
                learning_rate=0.05, subsample=0.8, colsample_bytree=0.8,
                scale_pos_weight=model.scale_pos_weight,
                random_state=42, verbosity=0, n_jobs=-1,
            )
        elif name == "LightGBM":
            cv_model = lgb.LGBMClassifier(
                n_estimators=model.best_iteration_ or 200, max_depth=6,
                learning_rate=0.05, subsample=0.8, colsample_bytree=0.8,
                class_weight="balanced", random_state=42, verbose=-1, n_jobs=-1,
            )
        else:
            cv_model = model

        cv_aucs = cross_val_score(cv_model, X_train, y_train,
                                   cv=cv, scoring="roc_auc", n_jobs=-1)

        metrics = {
            "accuracy":      round(accuracy_score(y_test, y_pred_opt), 4),
            "roc_auc":       round(roc_auc_score(y_test, y_prob), 4),
            "f1":            round(f1_score(y_test, y_pred_opt, zero_division=0), 4),
            "precision":     round(precision_score(y_test, y_pred_opt, zero_division=0), 4),
            "recall":        round(recall_score(y_test, y_pred_opt, zero_division=0), 4),
            "cv_auc_mean":   round(cv_aucs.mean(), 4),
            "cv_auc_std":    round(cv_aucs.std(), 4),
            "train_time_s":  round(elapsed, 2),
            "optimal_threshold": round(best_thresh, 3),
            "confusion_matrix": confusion_matrix(y_test, y_pred_opt).tolist(),
        }

        results[name] = metrics
        print(f"   AUC: {metrics['roc_auc']:.4f}  |  F1: {metrics['f1']:.4f}  |  "
              f"CV-AUC: {metrics['cv_auc_mean']:.4f} +/- {metrics['cv_auc_std']:.4f}  |  "
              f"Threshold: {best_thresh:.2f}  |  Time: {elapsed:.1f}s")

        # Save individual model
        save_name = name.lower().replace(" ", "")
        joblib.dump(model, MODELS_DIR / f"{save_name}.joblib")
        print(f"   Saved -> models/{save_name}.joblib")

    return results

# ─── 4. FEATURE IMPORTANCE ─────────────────────────────────────────────────────

def compute_importance(models):
    """Extract feature importances from trained models."""
    importance_data = {}
    for name, model in models.items():
        if name == "LogisticRegression":
            clf  = model.named_steps["clf"]
            imps = np.abs(clf.coef_[0])
        elif name in ("XGBoost", "LightGBM"):
            imps = model.feature_importances_
        else:
            continue
        imps = 100 * imps / (imps.sum() + 1e-10)
        importance_data[name] = dict(zip(FEATURE_NAMES, imps.round(2).tolist()))
    return importance_data

# ─── 5. PICK WINNER + SAVE REPORT ──────────────────────────────────────────────

def save_report(results, models, importance_data):
    """Pick best model by ROC-AUC, write comparison_report.json, set active."""
    winner = max(results, key=lambda m: results[m]["roc_auc"])

    report = {
        "winner":        winner,
        "metrics":       results,
        "importance":    importance_data,
        "feature_names": FEATURE_NAMES,
    }

    report_path = MODELS_DIR / "comparison_report.json"
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2)

    # Set winner as active model
    best_name = winner.lower().replace(" ", "")
    joblib.dump(models[winner], MODELS_DIR / "best_model.joblib")
    (MODELS_DIR / "best_model_name.txt").write_text(best_name)

    return winner

# ─── 6. PRINT SUMMARY ──────────────────────────────────────────────────────────

def print_summary(results, winner):
    print("\n" + "=" * 62)
    print(f"  Winner: {winner}")
    print("=" * 62)
    print(f"{'Model':<22} {'AUC':>7} {'F1':>6} {'Precision':>10} {'Recall':>8}")
    print("-" * 62)
    for name, m in results.items():
        flag = "  <-- winner" if name == winner else ""
        print(f"{name:<22} {m['roc_auc']:>7.4f} {m['f1']:>6.4f} "
              f"{m['precision']:>10.4f} {m['recall']:>8.4f}{flag}")
    print("=" * 62)
    print(f"\nModels saved to {MODELS_DIR}/")
    print(f"Report  saved to {MODELS_DIR}/comparison_report.json")
    print(f"Active model     set to: {winner.lower().replace(' ', '')}")

# ─── MAIN ──────────────────────────────────────────────────────────────────────

def run():
    print("=" * 62)
    print("  MORTGAGE AI — MULTI-MODEL TRAINER")
    print("=" * 62)

    X_train, X_test, y_train, y_test = load_data()
    models = build_models(y_train)
    results = train_and_evaluate(models, X_train, X_test, y_train, y_test)
    importance_data = compute_importance(models)
    winner = save_report(results, models, importance_data)
    print_summary(results, winner)
    return winner


if __name__ == "__main__":
    run()